### ISSUE TITLE
Creating a new user (teacher)

### ISSUE THREAD

**Issue by LuissForce** [KUJP-code/materials#29]
I created a teacher account with the admin permission, but when I clicked on create user it sent me to the error page. (small bug i think)
After accessing the page again, it successfully made the new teacher account

**Comment by Brett-Tanner** [comment]
This is because we don't have the ability to send emails, because we don't have a domain yet. It's trying to send an email to get the new user to confirm their email, but can't because we don't have a domain to send it from, so errors.

I should probably modify Devise a bit to put sending confirmation emails in a SolidQueue job to avoid this and just for general best practices.
