### ISSUE TITLE
Lesson guides cannot be PPT

### ISSUE THREAD

**Issue by LuissForce** [KUJP-code/materials#48]
I uploaded as a guide a powerpoint presentation and when i clicked saved it sent me to this screen 
![image](https://github.com/KUJP-code/materials/assets/161788348/98a5b01e-fe2e-4967-aad0-6c2ef194a9bc)

Usually when that happens they don't register, but this time they did, then in this list , I can't access them, when I click on them it sends me to the error page 
![image](https://github.com/KUJP-code/materials/assets/161788348/d1c2367d-3fb4-42f1-b291-0e85908a05d9)
![image](https://github.com/KUJP-code/materials/assets/161788348/3319eff9-22de-4591-8246-98d8da962828)

**Comment by Brett-Tanner** [comment]
It's because guides are meant to be PDFs, the app tries to generate a preview for the guide and can't do it because it can't generate previews of PPT files. You can't access the lesson page because there's a preview on that page which again, can't be generated from a PPT.

I recommend uploading a PDF version of the PPT as the guide, and the PPT version as a resource, which does not try to generate a guide. Then staff can choose to download either the PDF or PPT version (I personally always used a PDF of the slides).

**Comment by LuissForce** [comment]
Yes, but I can't access them to edit them/ delete them

**Comment by Brett-Tanner** [comment]
I'll manually fix them on Wednesday
