### ISSUE TITLE
Assign week or course

### ISSUE THREAD

**Issue by LuissForce** [KUJP-code/materials#5]
how about if from the activity list we assign the week and course, rather than in the guide itself
![3](https://github.com/KUJP-code/materials/assets/161788348/1431e1a2-5c94-4595-b621-4b393b20a9dd)

**Comment by Brett-Tanner** [comment]
The problem is that week/day is per course, whereas this is just a list of lessons without any relationships to their various courses. Would need to list the courses they're a part of and have day/week select boxes for each. 

Also, only admins are planned to be able to assign lessons to courses/weeks/days right now

**Comment by LuissForce** [comment]
Yes that could help.
but then who is checking the admin side? I think I should be able to comment on that too during this development stage, before assigning the real permissions haha

**Comment by Brett-Tanner** [comment]
Yeah that's why I wanted to get you set up with a local version, then you can check the admin side without having access to admin features on the live site. Can do that for you on Thursday. 

Ah true, that's in the form right? I'll hide that for non-admins.

**Comment by Brett-Tanner** [comment]
Luis now has testing access, and we're not adding date adjustment to the index as lessons can belong to many courses, which would make the table messy. Lesson dates for a course can be managed from the course page.
