### ISSUE TITLE
Students ID

### ISSUE THREAD

**Issue by LuissForce** [KUJP-code/materials#8]
![students](https://github.com/KUJP-code/materials/assets/161788348/11de9836-b022-4279-a2da-3bb9324ab322)
Is there a way to auto-assign consecutive student IDs? I was able to create several students with the same ID within the same class and school.

Another detail: I believe the school admin should have access to view the names of the students from this page. Access should be restricted for us (Kids UP) only if it's not a Kids Up school.
![image](https://github.com/KUJP-code/materials/assets/161788348/2b7783bc-f9f6-4b0a-b609-e89039d6bc66)

anyway if this admin page is only for kids up management and we are not supposed to see their names, once you click edit we can see the name.

**Comment by LuissForce** [comment]
![image](https://github.com/KUJP-code/materials/assets/161788348/a32b253c-2e32-4a75-a1bb-cf78007981ad)
also I guess this was Student ID right?

**Comment by Brett-Tanner** [comment]
> Is there a way to auto-assign consecutive student IDs?

No, because we want them to be able to use their existing student ids if they have them. Might add a fallback to the database id if they don't provide them since that does autoincrement and is better than nothing.

> able to create several students with the same ID within the same class and school

Yeah I thought of that too, you won't be able to after the next release on Thursday. I'll add a unique index on student ids per school, and maybe auto-prefix them with the school id to make sure they're unique per organisation.

> Access should be restricted for us (Kids UP) only if it's not a Kids Up school.

This is also in the next release, after finding out we'd be using it for our schools I changed it to compare the child and current user organisations rather than just checking if the current user was from KU

> once you click edit we can see the name.

ty, noted

**Comment by Brett-Tanner** [comment]
>  also I guess this was Student ID right?

Yeah, just no translation yet and the way it interpolates without a translation lops off the id

**Comment by Brett-Tanner** [comment]
Student ID issues closed by 5e11f191852639309480e260cd604703bc5862fc, f9e51ea107c89b616722bf81232e3014a2647c7c. Redaction issue closed by 194a6c494442bacd93695aa959306cf6a4d4ea0c.
